### ISSUE TITLE
Encryption methods

### ISSUE THREAD

**Issue by N1KD1** [faredus/gui-cipher-vignere#6]
There is only one method

**Comment by faredus** [comment]
i don't get it

**Comment by N1KD1** [comment]
> i don't get it

I mean to add a few more encryption methods

**Comment by faredus** [comment]
i don't think we've got enough time for that, the code is non modular rn and we have to remake it properly to add more methods (oop)

**Comment by N1KD1** [comment]
> i don't think we've got enough time for that, the code is non modular rn and we have to remake it properly to add more methods (oop)

Right
